# Generated by Django 2.2.19 on 2022-04-12 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dish_recipes', '0002_auto_20220412_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='FavoritesRecipe',
        ),
    ]
